version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes: 
      - ./docker-mysql-db:/var/lib/mysql
      - ./docker-backup-db:/backup
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci','--default-authentication-plugin=mysql_native_password', '--sql-mode=']
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  
  web:
    build: 
      context: .
    env_file: .env
    volumes: 
      - .:/var/www/html/vtiger740
    ports:
      - "${EXTERNAL_APACHE_PORT}:${APACHE_PORT}"
    depends_on: 
      db:
        condition: service_healthy